"""add agent nodes and agent skills

Revision ID: fa3325db9d0b
Revises: 95a4bb3e0a35
Create Date: 2026-08-05 05:53:06.760260+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'fa3325db9d0b'
down_revision: str | None = '95a4bb3e0a35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_nodes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_nodes')),
    sa.UniqueConstraint('role', name=op.f('uq_agent_nodes_role'))
    )
    op.create_table('agent_skills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('node_role', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('tool_grants_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_agent_skills_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_skills')),
    sa.UniqueConstraint('node_role', 'version', name='uq_agent_skills_role_version')
    )
    op.create_index('ix_agent_skills_role_active', 'agent_skills', ['node_role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_skills_role_active', table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_table('agent_nodes')
    # ### end Alembic commands ###
