"""add learn posts

Revision ID: 04804a601c7a
Revises: 0e805b2efc8f
Create Date: 2026-08-04 13:44:02.284680+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
revision: str = '04804a601c7a'
down_revision: str | None = '0e805b2efc8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `level` / `status` / `body_markdown` 都由 ORM 的 Python 侧 `default=` 在
    # insert 时填值（表从空开始），因此不需要 `server_default`。
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_posts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('author_user_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('cover_asset_id', sa.String(length=40), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_learn_posts_author_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], name=op.f('fk_learn_posts_cover_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_learn_posts_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learn_posts'))
    )
    op.create_index('ix_learn_posts_author', 'learn_posts', ['author_user_id'], unique=False)
    op.create_index('ix_learn_posts_status_published', 'learn_posts', ['status', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learn_posts_status_published', table_name='learn_posts')
    op.drop_index('ix_learn_posts_author', table_name='learn_posts')
    op.drop_table('learn_posts')
    # ### end Alembic commands ###
