"""add workflow input requests

Revision ID: 2c39f9f7a4ea
Revises: 5bc23ff7e383
Create Date: 2026-08-12 11:40:01.765848+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2c39f9f7a4ea'
down_revision: str | None = '5bc23ff7e383'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_input_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('output_key', sa.String(length=40), nullable=False),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_checkpoint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_workflow_input_requests_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_input_requests')),
    sa.UniqueConstraint('job_id', name=op.f('uq_workflow_input_requests_job_id'))
    )
    op.create_index('ix_workflow_input_requests_expires_at', 'workflow_input_requests', ['expires_at'], unique=False)
    # ### end Alembic commands ###
    # Autogenerate also picked up unrelated server_default drift on
    # `agent_nodes`/`agent_profiles`/`provider_async_tasks` from other
    # in-flight work — dropped here so this migration only touches the new
    # table, per the "只建表，不动存量表" rule for this change.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_input_requests_expires_at', table_name='workflow_input_requests')
    op.drop_table('workflow_input_requests')
    # ### end Alembic commands ###
