"""add system logs

Revision ID: c410ddccb37d
Revises: 85078b4d8040
Create Date: 2026-08-05 09:37:11.455494+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c410ddccb37d"
down_revision: str | None = "85078b4d8040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_logs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_logs")),
        sa.UniqueConstraint(
            "source", "event", "dedup_key", "window_started_at", name="uq_system_logs_window"
        ),
    )
    op.create_index("ix_system_logs_created_at", "system_logs", ["created_at"], unique=False)
    op.create_index("ix_system_logs_source_event", "system_logs", ["source", "event"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_system_logs_source_event", table_name="system_logs")
    op.drop_index("ix_system_logs_created_at", table_name="system_logs")
    op.drop_table("system_logs")
    # ### end Alembic commands ###
