"""add generation workflow templates

Revision ID: 403d2794785b
Revises: c410ddccb37d
Create Date: 2026-08-05 14:27:34.572169+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '403d2794785b'
down_revision: str | None = 'c410ddccb37d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_workflow_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_generation_workflow_templates_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_workflow_templates')),
    sa.UniqueConstraint('operation', 'version', name='uq_generation_workflow_templates_op_version')
    )
    op.create_index('ix_generation_workflow_templates_operation_active', 'generation_workflow_templates', ['operation', 'is_active'], unique=False)
    op.add_column('generation_jobs', sa.Column('workflow_template_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(op.f('fk_generation_jobs_workflow_template_id_generation_workflow_templates'), 'generation_jobs', 'generation_workflow_templates', ['workflow_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_generation_jobs_workflow_template_id_generation_workflow_templates'), 'generation_jobs', type_='foreignkey')
    op.drop_column('generation_jobs', 'workflow_template_id')
    op.drop_index('ix_generation_workflow_templates_operation_active', table_name='generation_workflow_templates')
    op.drop_table('generation_workflow_templates')
    # ### end Alembic commands ###
