"""add creation skills

Revision ID: 243748f19723
Revises: fa3325db9d0b
Create Date: 2026-08-05 06:14:40.386134+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '243748f19723'
down_revision: str | None = 'fa3325db9d0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creation_skills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_asset_id', sa.String(length=40), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], name=op.f('fk_creation_skills_cover_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_creation_skills_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_creation_skills_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creation_skills'))
    )
    op.create_index('ix_creation_skills_owner', 'creation_skills', ['owner_user_id'], unique=False)
    op.create_index('ix_creation_skills_status_created', 'creation_skills', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_creation_skills_status_created', table_name='creation_skills')
    op.drop_index('ix_creation_skills_owner', table_name='creation_skills')
    op.drop_table('creation_skills')
    # ### end Alembic commands ###
