"""add agent run endpoint id

Revision ID: 95a4bb3e0a35
Revises: 04804a601c7a
Create Date: 2026-08-05 05:46:10.738239+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '95a4bb3e0a35'
down_revision: str | None = '04804a601c7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('endpoint_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'endpoint_id')
    # ### end Alembic commands ###
