"""add redemption codes

Revision ID: 85078b4d8040
Revises: 243748f19723
Create Date: 2026-08-05 08:10:14.397431+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '85078b4d8040'
down_revision: str | None = '243748f19723'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemption_codes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name=op.f('ck_redemption_codes_credits_positive')),
    sa.CheckConstraint('max_uses > 0', name=op.f('ck_redemption_codes_max_uses_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_redemption_codes_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redemption_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_redemption_codes_code'))
    )
    op.create_table('redemption_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['redemption_codes.id'], name=op.f('fk_redemption_records_code_id_redemption_codes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_redemption_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redemption_records')),
    sa.UniqueConstraint('code_id', 'user_id', name='uq_redemption_records_code_user')
    )
    op.create_index('ix_redemption_records_user', 'redemption_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_redemption_records_user', table_name='redemption_records')
    op.drop_table('redemption_records')
    op.drop_table('redemption_codes')
    # ### end Alembic commands ###
