"""add style gallery entries

Revision ID: b2e99848e1ca
Revises: 52b80f3f3f8f
Create Date: 2026-08-11 15:19:40.176816+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'b2e99848e1ca'
down_revision: str | None = '52b80f3f3f8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_gallery_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label_zh', sa.String(length=64), nullable=False),
    sa.Column('label_en', sa.String(length=64), nullable=False),
    sa.Column('label_ja', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_asset_id', sa.String(length=40), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('apply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], name=op.f('fk_style_gallery_entries_cover_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_gallery_entries')),
    sa.UniqueConstraint('slug', name=op.f('uq_style_gallery_entries_slug'))
    )
    op.create_index('ix_style_gallery_entries_active_sort', 'style_gallery_entries', ['is_active', 'sort_order'], unique=False)
    # ### end Alembic commands ###
    # Autogenerate also picked up unrelated server_default drift on
    # `agent_nodes`/`agent_profiles`/`provider_async_tasks` from other
    # in-flight work — dropped here so this migration only touches the new
    # table, per the "只建表，不动存量表" rule for this change.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_style_gallery_entries_active_sort', table_name='style_gallery_entries')
    op.drop_table('style_gallery_entries')
    # ### end Alembic commands ###
