"""add characters and series

Revision ID: 65d2fccc916c
Revises: 842f9d1d6c19
Create Date: 2026-08-03 08:55:37.457398+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '65d2fccc916c'
down_revision: str | None = '842f9d1d6c19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_asset_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('voice_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_characters_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    op.create_index('ix_characters_owner_user_id', 'characters', ['owner_user_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shortform_profile_key', sa.String(length=64), nullable=True),
    sa.Column('character_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_series_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    op.create_index('ix_series_owner_user_id', 'series', ['owner_user_id'], unique=False)
    op.add_column('works', sa.Column('series_id', sa.String(length=40), nullable=True))
    op.add_column('works', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.create_index('ix_works_series_id_episode_number', 'works', ['series_id', 'episode_number'], unique=False)
    op.create_foreign_key(op.f('fk_works_series_id_series'), 'works', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_works_series_id_series'), 'works', type_='foreignkey')
    op.drop_index('ix_works_series_id_episode_number', table_name='works')
    op.drop_column('works', 'episode_number')
    op.drop_column('works', 'series_id')
    op.drop_index('ix_series_owner_user_id', table_name='series')
    op.drop_table('series')
    op.drop_index('ix_characters_owner_user_id', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
