"""add series genre platform logo metadata

Revision ID: b14aeed5566e
Revises: 3c8e1f4a9d02
Create Date: 2026-08-27 05:58:40.517584+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'b14aeed5566e'
down_revision: str | None = '3c8e1f4a9d02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('english_title', sa.String(length=200), nullable=True))
    op.add_column('series', sa.Column('planned_episode_count', sa.Integer(), nullable=True))
    # `server_default='[]'` covers every pre-existing row (including
    # `kind=cast` roster rows, which never populate these) for a safe
    # NOT NULL upgrade — see `zaolang-data-model` invariant on adding columns.
    op.add_column(
        'series',
        sa.Column(
            'genre_tags_json',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='[]',
            nullable=False,
        ),
    )
    op.add_column(
        'series',
        sa.Column(
            'target_platforms_json',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='[]',
            nullable=False,
        ),
    )
    op.add_column('series', sa.Column('logo_asset_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(op.f('fk_series_logo_asset_id_assets'), 'series', 'assets', ['logo_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_series_logo_asset_id_assets'), 'series', type_='foreignkey')
    op.drop_column('series', 'logo_asset_id')
    op.drop_column('series', 'target_platforms_json')
    op.drop_column('series', 'genre_tags_json')
    op.drop_column('series', 'planned_episode_count')
    op.drop_column('series', 'english_title')
    # ### end Alembic commands ###
