"""add statistics and pagination indexes

Revision ID: 23b7404b3ff1
Revises: a3f8c2d91e04
Create Date: 2026-08-29 08:44:57.549391+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "23b7404b3ff1"
down_revision: str | None = "a3f8c2d91e04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate also proposed dropping the `server_default` on
    # `agent_runs.thinking_text` / `drafts.publish_params_json` /
    # `episode_script_turns.thinking_text` — pre-existing drift unrelated to
    # this change (the model only declares a Python-side `default`). Left out
    # on purpose to keep this migration to the index additions it is named
    # for; that drift is tracked separately.
    op.create_index("ix_agent_runs_created_at", "agent_runs", ["created_at"], unique=False)
    op.create_index(
        "ix_collection_items_collection_id_position",
        "collection_items",
        ["collection_id", "position"],
        unique=False,
    )
    op.create_index(
        "ix_collections_owner_user_id_created_at",
        "collections",
        ["owner_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_credit_ledger_created_at", "credit_ledger_entries", ["created_at"], unique=False
    )
    op.create_index(
        "ix_generation_jobs_created_at", "generation_jobs", ["created_at"], unique=False
    )
    op.create_index("ix_lineage_edges_created_at", "lineage_edges", ["created_at"], unique=False)
    op.create_index(
        "ix_provider_attempts_created_at", "provider_attempts", ["created_at"], unique=False
    )
    op.create_index("ix_system_logs_updated_at", "system_logs", ["updated_at"], unique=False)
    op.create_index("ix_users_created_at", "users", ["created_at"], unique=False)
    op.create_index("ix_works_like_count_id", "works", ["like_count", "id"], unique=False)
    op.create_index("ix_works_remix_count_id", "works", ["remix_count", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_works_remix_count_id", table_name="works")
    op.drop_index("ix_works_like_count_id", table_name="works")
    op.drop_index("ix_users_created_at", table_name="users")
    op.drop_index("ix_system_logs_updated_at", table_name="system_logs")
    op.drop_index("ix_provider_attempts_created_at", table_name="provider_attempts")
    op.drop_index("ix_lineage_edges_created_at", table_name="lineage_edges")
    op.drop_index("ix_generation_jobs_created_at", table_name="generation_jobs")
    op.drop_index("ix_credit_ledger_created_at", table_name="credit_ledger_entries")
    op.drop_index("ix_collections_owner_user_id_created_at", table_name="collections")
    op.drop_index("ix_collection_items_collection_id_position", table_name="collection_items")
    op.drop_index("ix_agent_runs_created_at", table_name="agent_runs")
    # ### end Alembic commands ###
