"""SQLAlchemy models.

Everything is re-exported here so that `Base.metadata` is fully populated by a
single import, which is what Alembic autogenerate relies on.
"""

from app.models.access import AccessGrant
from app.models.agent_skills import AgentNode, AgentProfile, AgentSkill
from app.models.async_tasks import AsyncProviderTask
from app.models.base import Base, TimestampMixin, new_id, utcnow
from app.models.canvas import (
    CanvasAgentRun,
    CanvasAgentTask,
    CanvasChange,
    CanvasEdge,
    CanvasNode,
    CanvasProject,
)
from app.models.characters import Series, SeriesCollaborator
from app.models.credits import (
    CreditAccount,
    CreditLedgerEntry,
    CreditPackage,
    PaymentIntent,
    RedemptionCode,
    RedemptionRecord,
    WebhookEvent,
)
from app.models.distribution import (
    EpisodeExternalMetric,
    EpisodeExternalMetricDaily,
    PlatformAccountDailyStat,
    PlatformAccountLink,
)
from app.models.editor import (
    CutRevision,
    DeliveryVariant,
    DramaEpisode,
    EditorCommandEvent,
    EditorExport,
    EditorLease,
    EditorOperationEvent,
    EditPlan,
    EpisodeBlockingVersion,
    EpisodeContentLink,
    EpisodeCut,
    EpisodeScriptTurn,
    McpTokenGrant,
    MediaAnalysis,
)
from app.models.generation import (
    AgentRun,
    GenerationJob,
    GenerationWorkflowTemplate,
    JobEvent,
    ProviderAttempt,
    ProviderStat,
    Workflow,
    WorkflowVersion,
)
from app.models.identity import Follow, Profile, User
from app.models.learning import LearnPost
from app.models.media import (
    Asset,
    AssetConsent,
    ContentFingerprint,
    ProvenanceManifest,
    UploadSession,
)
from app.models.platform import (
    Announcement,
    AuditLog,
    BackupRecord,
    DataRequest,
    Device,
    IdempotencyRecord,
    ModerationQueueItem,
    ModerationResult,
    Notification,
    PlatformConfig,
    ReconciliationReport,
    ReportCase,
    WorkAppeal,
)
from app.models.search import EMBEDDING_DIM, WorkEmbedding
from app.models.skill_library import CreationSkill
from app.models.style_gallery import StyleGalleryEntry
from app.models.system_log import SystemLog
from app.models.workflow_input import WorkflowInputRequest
from app.models.works import (
    Bookmark,
    Collection,
    CollectionItem,
    Draft,
    LicenseSnapshot,
    Like,
    LineageEdge,
    PublicationIntent,
    StylePreset,
    Tag,
    Work,
    WorkTag,
    WorkVersion,
)

__all__ = [
    "EMBEDDING_DIM",
    "AccessGrant",
    "AgentNode",
    "AgentProfile",
    "AgentRun",
    "AgentSkill",
    "Announcement",
    "Asset",
    "AssetConsent",
    "AsyncProviderTask",
    "AuditLog",
    "BackupRecord",
    "Base",
    "Bookmark",
    "CanvasAgentRun",
    "CanvasAgentTask",
    "CanvasChange",
    "CanvasEdge",
    "CanvasNode",
    "CanvasProject",
    "Collection",
    "CollectionItem",
    "ContentFingerprint",
    "CreationSkill",
    "CreditAccount",
    "CreditLedgerEntry",
    "CreditPackage",
    "CutRevision",
    "DataRequest",
    "DeliveryVariant",
    "Device",
    "Draft",
    "DramaEpisode",
    "EditPlan",
    "EditorCommandEvent",
    "EditorExport",
    "EditorLease",
    "EditorOperationEvent",
    "EpisodeBlockingVersion",
    "EpisodeContentLink",
    "EpisodeCut",
    "EpisodeExternalMetric",
    "EpisodeExternalMetricDaily",
    "EpisodeScriptTurn",
    "Follow",
    "GenerationJob",
    "GenerationWorkflowTemplate",
    "IdempotencyRecord",
    "JobEvent",
    "LearnPost",
    "LicenseSnapshot",
    "Like",
    "LineageEdge",
    "McpTokenGrant",
    "MediaAnalysis",
    "ModerationQueueItem",
    "ModerationResult",
    "Notification",
    "PaymentIntent",
    "PlatformAccountDailyStat",
    "PlatformAccountLink",
    "PlatformConfig",
    "Profile",
    "ProvenanceManifest",
    "ProviderAttempt",
    "ProviderStat",
    "PublicationIntent",
    "ReconciliationReport",
    "RedemptionCode",
    "RedemptionRecord",
    "ReportCase",
    "Series",
    "SeriesCollaborator",
    "StyleGalleryEntry",
    "StylePreset",
    "SystemLog",
    "Tag",
    "TimestampMixin",
    "UploadSession",
    "User",
    "WebhookEvent",
    "Work",
    "WorkAppeal",
    "WorkEmbedding",
    "WorkTag",
    "WorkVersion",
    "Workflow",
    "WorkflowInputRequest",
    "WorkflowVersion",
    "new_id",
    "utcnow",
]
